2022-12-06 14:16:16.722 [error] <0.282.0> Supervisor {<0.282.0>,amqp_channel_sup_sup} had child channel_sup started with amqp_channel_sup:start_link(network, <0.279.0>, <<"client 127.0.0.1:55762 -> 127.0.0.1:5672">>) at undefined exit with reason shutdown in context shutdown_error
2022-12-06 20:36:29.940 [error] <0.455.0>@Elixir.StreamReader:handle_info:31 gen_server <0.455.0> terminated with reason: no function clause matching 'Elixir.StreamReader':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-TNJVlFEsuIPOzMmZeUwqCQ">>}}, #{'__struct__' => 'Elixir.StreamReader',connection => #{'__struct__' => 'Elixir.AMQP.Connection',...},...}) line 31
2022-12-06 20:36:29.941 [error] <0.455.0>@Elixir.StreamReader:handle_info:31 CRASH REPORT Process <0.455.0> with 4 neighbours crashed with reason: no function clause matching 'Elixir.StreamReader':handle_info({basic_consume_ok,#{consumer_tag => <<"amq.ctag-TNJVlFEsuIPOzMmZeUwqCQ">>}}, #{'__struct__' => 'Elixir.StreamReader',connection => #{'__struct__' => 'Elixir.AMQP.Connection',...},...}) line 31
2022-12-06 20:38:00.610 [error] <0.411.0> gen_server <0.411.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-12-06 20:38:00.610 [error] <0.411.0> CRASH REPORT Process <0.411.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-12-06 20:38:00.610 [error] <0.410.0> Supervisor {<0.410.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57114 -> 127.0.0.1:5672">>,1}) at <0.411.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-12-06 20:38:00.610 [error] <0.410.0> Supervisor {<0.410.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57114 -> 127.0.0.1:5672">>,1}) at <0.411.0> exit with reason reached_max_restart_intensity in context shutdown
2022-12-06 20:38:00.610 [error] <0.307.0> gen_server <0.307.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-12-06 20:38:00.610 [error] <0.359.0> gen_server <0.359.0> terminated with reason: unexpected_delivery_and_no_default_consumer
2022-12-06 20:38:00.610 [error] <0.307.0> CRASH REPORT Process <0.307.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-12-06 20:38:00.610 [error] <0.359.0> CRASH REPORT Process <0.359.0> with 0 neighbours exited with reason: unexpected_delivery_and_no_default_consumer in gen_server2:terminate/3 line 1183
2022-12-06 20:38:00.610 [error] <0.308.0> gen_server <0.308.0> terminated with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.307.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-WvyLjAM5yvGWmpbqrNzIcw">>,1,false,<<"logs">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"ala">>}},70000]}} in gen_server2:call/3 line 346
2022-12-06 20:38:00.610 [error] <0.358.0> Supervisor {<0.358.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57101 -> 127.0.0.1:5672">>,1}) at <0.359.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-12-06 20:38:00.610 [error] <0.358.0> Supervisor {<0.358.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57101 -> 127.0.0.1:5672">>,1}) at <0.359.0> exit with reason reached_max_restart_intensity in context shutdown
2022-12-06 20:38:00.610 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57097 -> 127.0.0.1:5672">>,1}) at <0.307.0> exit with reason unexpected_delivery_and_no_default_consumer in context child_terminated
2022-12-06 20:38:00.610 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child gen_consumer started with amqp_gen_consumer:start_link(amqp_selective_consumer, [], {<<"client 127.0.0.1:57097 -> 127.0.0.1:5672">>,1}) at <0.307.0> exit with reason reached_max_restart_intensity in context shutdown
2022-12-06 20:38:00.610 [error] <0.308.0> CRASH REPORT Process <0.308.0> with 0 neighbours exited with reason: {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.307.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-WvyLjAM5yvGWmpbqrNzIcw">>,1,false,<<"logs">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"ala">>}},70000]}} in gen_server2:call/3 line 346
2022-12-06 20:38:00.611 [error] <0.306.0> Supervisor {<0.306.0>,amqp_channel_sup} had child channel started with amqp_channel:start_link(network, <0.297.0>, 1, <0.307.0>, {<<"client 127.0.0.1:57097 -> 127.0.0.1:5672">>,1}) at <0.308.0> exit with reason {unexpected_delivery_and_no_default_consumer,{gen_server2,call,[<0.307.0>,{consumer_call,{'basic.deliver',<<"amq.ctag-WvyLjAM5yvGWmpbqrNzIcw">>,1,false,<<"logs">>,<<>>},{amqp_msg,{'P_basic',undefined,undefined,undefined,1,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined,undefined},<<"ala">>}},70000]}} in context shutdown_error
2022-12-06 20:38:00.611 [error] <0.297.0> gen_server <0.297.0> terminated with reason: {channel0_died,method_field_shortstr_overflow}
2022-12-06 20:38:00.611 [error] <0.297.0> CRASH REPORT Process <0.297.0> with 0 neighbours exited with reason: {channel0_died,method_field_shortstr_overflow} in gen_server:handle_common_reply/8 line 1241
2022-12-06 20:38:00.611 [error] <0.295.0> Supervisor {<0.295.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.296.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.297.0> exit with reason {channel0_died,method_field_shortstr_overflow} in context child_terminated
2022-12-06 20:38:00.611 [error] <0.295.0> Supervisor {<0.295.0>,amqp_connection_sup} had child connection started with amqp_gen_connection:start_link(<0.296.0>, {amqp_params_network,<<"guest">>,{plaintext,<<"guest">>},<<"/">>,"localhost",5672,0,0,10,50000,none,...}) at <0.297.0> exit with reason reached_max_restart_intensity in context shutdown
